--INDEX FOR EMPLOYEE----
CREATE INDEX EMPLOYEE_LAST_NAME_IX
ON EMPLOYEE(LAST_NAME);
CREATE INDEX EMPLOYEE_FIRST_NAME_IX
ON EMPLOYEE(FIRST_NAME);
CREATE INDEX EMPLOYEE_EMP_TYPE_IX
ON EMPLOYEE(EMP_TYPE);
CREATE INDEX EMPLOYEE_HOME_LANGUAGE_IX
ON EMPLOYEE(HOME_LANGUAGE);


----INDEX FOR PRESENTER-----
CREATE INDEX PRESENTER_TOT_HOURS_WEEK_IX
ON PRESENTER(TOT_HOURS_WEEK);
CREATE INDEX PRESENTER_SKILLS_IX
ON PRESENTER(TOP_SKILL);
CREATE INDEX PRESENTER_POSITION_IX
ON PRESENTER(CURRENT_POSITION);


---INDEX FOR PROGRAM----
CREATE INDEX PROGRAM_PROGRAM_NAME_IX
ON PROGRAM_(PROGRAM_NAME);
CREATE INDEX PROGRAM_PROGRAM_DURATION_IX
ON PROGRAM_(PROGRAM_DURATION);
CREATE INDEX PROGRAM_STARTING_TIME_IX
ON PROGRAM_(STARTING_TIME);
CREATE INDEX PROGRAM_CATEGORY_IX
ON PROGRAM_(CATEGORY);
CREATE INDEX NUM_OF_SONGS_TOPLAY_IX
ON PROGRAM_(NUM_OF_SONGS_TOPLAY);
CREATE INDEX PROGRAM_TOPIC_IX
ON PROGRAM_(PROGRAM_TOPIC);
CREATE INDEX NEWS_UPDATES_IX
ON PROGRAM_(NEWS_UPDATES);
CREATE INDEX ADVERT_AIRPLAY_IX
ON PROGRAM_(ADVERT_AIRPLAY);

----INDEX FOR SONGS----
CREATE INDEX MUSIC_TITLE_IX
ON MUSIC(TITLE);
CREATE INDEX MUSIC_GENRE_IX
ON MUSIC(GENRE);
CREATE INDEX MUSIC_AIRTIST_NAME_IX
ON MUSIC(ARTIST_NAME);
CREATE INDEX MUSIC_RECORD_LABEL_IX
ON MUSIC(RECORD_LABEL);
CREATE INDEX MUSIC_PROG_ID_IX
ON MUSIC(PROG_ID);

---INDEX FOR GUEST---
CREATE INDEX GUEST_GUEST_NAME_IX
ON GUEST(GUEST_NAME);
CREATE INDEX GUEST_AGENDA_IX
ON GUEST(AGENDA);

---INDEX FOR EQUIPMENT---
CREATE INDEX EQUIPMENT_EQUIP_NAME_IX
ON EQUIPMENT(EQUIP_NAME);
CREATE INDEX EQUIMENT_EQUIP_TYPE_IX
ON EQUIPMENT(EQUIP_TYPE);
CREATE INDEX EQUIPMENT_MAINTANANCE_DATE_IX
ON EQUIPMENT(MAINTANANCE_DATE);

---INDEX FOR ROOM---
CREATE INDEX ROOM_AREA_IX
ON ROOM(AREA);