SELECT * FROM EMPLOYEE;
SELECT * FROM PRESENTER;
SELECT * FROM PROGRAM_;
SELECT * FROM EQUIPMENT;
SELECT * FROM ROOM;
SELECT * FROM GUEST;
SELECT * FROM MUSIC;

-----LIMITAION OF ROWS AND COLUMNS-----
SELECT LAST_NAME,FIRST_NAME,EMP_TYPE,GENDER,CONTACT_NUMBER 
FROM EMPLOYEE WHERE SALARY<2600;

SELECT EMP_ID,CURRENT_POSITION,TOP_SKILL
FROM PRESENTER WHERE TOT_HOURS_WEEK<21;


------SORTING-----
SELECT * FROM EMPLOYEE ORDER BY LAST_NAME ASC;
SELECT * FROM PRESENTER ORDER BY EMP_ID ASC;
SELECT * FROM MUSIC ORDER BY TITLE ASC;
SELECT * FROM GUEST ORDER BY GUEST_NAME ASC;
SELECT * FROM EQUIPMENT ORDER BY EQUIP_ID ASC;
SELECT * FROM ROOM ORDER BY ROOM_NUM ASC; 
SELECT * FROM PROGRAM_ ORDER BY STARTING_TIME ASC;

-----LIKE, AND, OR -----
SELECT LAST_NAME,FIRST_NAME, AGE,EMP_TYPE,SALARY,HOMETOWN,GENDER,CONTACT_NUMBER
FROM EMPLOYEE
WHERE AGE>20 AND GENDER ='MALE';

SELECT EMP_ID,TOT_HOURS_WEEK,TOP_SKILL,CURRENT_POSITION
FROM PRESENTER
WHERE CURRENT_POSITION='DJ' OR CURRENT_POSITION='TALKSHOW'
ORDER BY CURRENT_POSITION;

SELECT * FROM EMPLOYEE 
WHERE (EMP_TYPE LIKE 'PR%') OR (EMP_TYPE LIKE 'S%')
ORDER BY EMP_TYPE;


---CHARACTER FUNCTIONS---
SELECT PROGRAM_NAME, INITCAP(PROGRAM_TOPIC) AS PROGRAM_TOPIC FROM PROGRAM_; ----MAKE LETTER UPPERCASE OR LOWERCASE
SELECT EQUIP_NAME, ROUND(MONTHS_BETWEEN(maintanance_date,SYSDATE)) AS MAINTANACE_MONTHS ---THE NUMBER OF MONTHS REMAINING FOR THE NEXT MAINTANANCE
FROM EQUIPMENT;
SELECT COUNT(EQUIP_ID) AS NUM_OF_EQUIP ----TOTAL TYPES OF EQUIPMENTS
FROM ROOM;
SELECT CONCAT(LAST_NAME,FIRST_NAME)AS FULL_NAME FROM EMPLOYEE;


---DATE FUNCTIONS INCLUDING TRUNC------
SELECT TRUNC(EMP_HIREDATE,'YY') AS HIREDATE_YEARS FROM EMPLOYEE; 

SELECT * FROM EMPLOYEE WHERE EMP_HIREDATE = '12/NOV/10'; /*Shows only dates that are "12/NOV/10" */

SELECT * FROM EQUIPMENT WHERE MAINTANANCE_DATE > '30/APR/21'; /*Shows maintenance dates FROM 01 MAY 2021.*/


---- AGGREGATE FUNCTIONS-----
SELECT MAX(SALARY),MIN(SALARY)
FROM EMPLOYEE WHERE EMP_TYPE ='STATION-MANAGER';

SELECT COUNT(*)
FROM EQUIPMENT WHERE quantity>10;

SELECT MIN(AGE),MAX(AGE)
FROM EMPLOYEE WHERE SALARY>1500;

---GROUP BY HAVING----
SELECT highest_certificate,AGE,SALARY FROM employee GROUP BY highest_certificate,AGE, SALARY HAVING SALARY >2000;

SELECT  FIRST_NAME,EMP_TYPE,AGE FROM employee GROUP BY FIRST_NAME,EMP_TYPE,AGE HAVING AGE BETWEEN 20 AND 25;

SELECT LAST_NAME, FIRST_NAME,GENDER,EMP_ID FROM employee GROUP BY LAST_NAME, FIRST_NAME,GENDER,EMP_ID HAVING EMP_ID <1111;

