

CREATE VIEW EMPLOYEE_PUBLIC AS
SELECT LAST_NAME,FIRST_NAME,EMP_TYPE,HOME_LANGUAGE
FROM EMPLOYEE;

CREATE VIEW PRESENTER_PUBLIC AS
SELECT EMP_ID, TOT_HOURS_WEEK,TOP_SKILL,CURRENT_POSITION
FROM PRESENTER;

CREATE VIEW PROGRAM_PUBLIC AS
SELECT PROGRAM_NAME,PROGRAM_DURATION,STARTING_TIME,CATEGORY,NUM_OF_SONGS_TOPLAY,PROGRAM_TOPIC,NEWS_UPDATES,ADVERT_AIRPLAY
FROM PROGRAM_;

CREATE VIEW MUSIC_PUBLIC AS
SELECT TITLE,GENRE,ARTIST_NAME,RECORD_LABEL,PROG_ID
FROM MUSIC;

CREATE VIEW GUEST_PUBLIC AS
SELECT GUEST_NAME,AGENDA
FROM GUEST;

CREATE VIEW EQUIPMENT_PUBLIC AS
SELECT EQUIP_NAME,EQUIP_TYPE,MAINTANANCE_DATE
FROM EQUIPMENT;

CREATE VIEW ROOM_PUBLIC AS
SELECT ROOM_NUM,AREA
FROM ROOM;
